### ISSUE TITLE
The meaning of progress

### ISSUE THREAD

**Issue by gaow0007** [petuum/adaptdl#104]
When I implement trace collection in your osdi21-artifact branch. 
I am a little confuse the meaning of progress in [validation-2048.csv](https://github.com/petuum/adaptdl/blob/osdi21-artifact/simulator/traces/cifar10/validation-2048.csv). 
I obtain progress information via [get_progress](https://github.com/petuum/adaptdl/blob/d83e4ceef0cf3863d842bb2744181379cc3cd0e7/adaptdl/adaptdl/torch/_metrics.py#L83). 
However, it seems not mismatch your released trace information. 
My collected batch=128 trace information. 
![image](https://user-images.githubusercontent.com/16629752/138204897-9781432b-1561-443d-877d-e8667d501ec5.png)

My collected batch=2048 trace information.
![image](https://user-images.githubusercontent.com/16629752/138204977-fbf03d7b-6204-4238-83a0-0ba1856081de.png)

May I ask some suggestions to mitigate the mismatch?

**Comment by aurickq** [comment]
Hi @gaow0007, apologies for the late reply. `progress` means the number of iterations discounted by the statistical efficiency. For example, 200 iterations at 50% statistical efficiency translates to "progress" of 100. This is based on theory so may not exactly match in practice.

For your experiments, one thing I can think of is to make sure you are changing the scaled-up batch size (M) and not the baseline batch size (M_0). The batch_size parameter for the DataLoader class is the baseline batch size for Pollux. To set a fixed scaled-up batch size, you should set the `TARGET_BATCH_SIZE` environment variable instead. Sorry this part is not well documented.

**Comment by gaow0007** [comment]
Thanks for your explanation.

**Comment by gaow0007** [comment]
A further question: Where does TARGET_BATCH_SIZE  work in the code? I fail to search such key word. @aurickq

**Comment by aurickq** [comment]
> A further question: Where does TARGET_BATCH_SIZE  work in the code? I fail to search such key word. @aurickq 

https://github.com/petuum/adaptdl/blob/osdi21-artifact/adaptdl/adaptdl/torch/data.py

On line 266.

**Comment by gaow0007** [comment]
Thanks for your reply.
