### ISSUE TITLE
Problems encountered during the installation of AdaptDL Helm Chart

### ISSUE THREAD

**Issue by prz30** [petuum/adaptdl#106]
when i installed AdaptDL Helm Chart by using this command :
helm install adaptdl adaptdl-sched --repo https://github.com/petuum/adaptdl/raw/helm-repo --namespace adaptdl --create-namespace --set docker-registry.enabled=true

i geted the following error:
Error: INSTALLATION FAILED: looks like "https://github.com/petuum/adaptdl/raw/helm-repo" is not a valid chart repository or cannot be reached: Get "https://github.com/petuum/adaptdl/raw/helm-repo/index.yaml": dial tcp 20.205.243.166:443: connect: connection timed out
![image](https://user-images.githubusercontent.com/37689034/144340599-6eae3b87-1b46-4452-a142-2fa15ef7bf5a.png)
please tell me how can i solve this error，thanks

**Comment by rmfan** [comment]
Can you manually reach [https://raw.githubusercontent.com/petuum/adaptdl/helm-repo/index.yaml](https://raw.githubusercontent.com/petuum/adaptdl/helm-repo/index.yaml)? 

If so, can you try running the command `helm repo add adaptdl https://raw.githubusercontent.com/petuum/adaptdl/helm-repo`? 

If that works, try running `helm repo update`, followed by `helm search repo adaptdl-sched`. Ideally, you should see `adaptdl-sched` with version `0.2.8`.

If all of that works correctly, try running 
```helm install adaptdl adaptdl/adaptdl-sched --namespace adaptdl --create-namespace --set docker-registry.enabled=true```

**Comment by prz30** [comment]
> Can you manually reach https://raw.githubusercontent.com/petuum/adaptdl/helm-repo/index.yaml?
> 
> If so, can you try running the command `helm repo add adaptdl https://raw.githubusercontent.com/petuum/adaptdl/helm-repo`?
> 
> If that works, try running `helm repo update`, followed by `helm search repo adaptdl-sched`. Ideally, you should see `adaptdl-sched` with version `0.2.8`.
> 
> If all of that works correctly, try running `helm install adaptdl adaptdl/adaptdl-sched --namespace adaptdl --create-namespace --set docker-registry.enabled=true`
> 
> Let me know if you run into issues or errors during any of those steps.

I can reach https://raw.githubusercontent.com/petuum/adaptdl/helm-repo/index.yaml on my computer, but i can't get this link on my server. I think it's my problem. thanks  for your help.
