### ISSUE TITLE
Plans to include UI for scheduler?

### ISSUE THREAD

**Issue by radao** [petuum/adaptdl#59]
We are investigating adaptdl's command line interface to use as a scheduler for our gpu cluster and are wondering if there are plans to include a UI to view submitted jobs, output files, etc? I see an issue already for Kubeflow integration, which has a UI to display these sort of things, so that could be one solution.

**Comment by aurickq** [comment]
Hi @radao, we are currently working on a UI, but it's not finished yet. Would you care to share some specific UI features you are looking for? We might be able to help you address them. For the output files issue, you might be able to use something like [JupyterLab](https://jupyterlab.readthedocs.io/en/stable/user/files.html) to view and download the files from your cluster.

By the way, you can also email us at opensource (at) petuum (dot) com if you prefer to communicate that way.

**Comment by radao** [comment]
Hey @aurickq, thanks for the prompt response! I'd say to start viewing the info available via the cli would already be helpful, so mainly the output of `adaptdl ls` (job name, status, times). Additional info that would be useful:

1. Requested/allocated resources for each job
2. User name associated with each job
3. Cluster status
4. Stdout/stderr

It would also be nice to interact with jobs via the UI, like deleting jobs, viewing output files generated (and ideally downloading them), submitting jobs via the UI, launching tensorboard instances, etc.

We're also evaluating [Microsoft's OpenPAI](https://openpai.readthedocs.io) for scheduling as it has a pretty nice UI already. It may be helpful to have a look there for inspiration.
