### ISSUE TITLE
Benchmark Dataset for DeepSpeech2 in Pollux 

### ISSUE THREAD

**Issue by lynnliu030** [petuum/adaptdl#96]
Hi, in the osdi21-artifact branch, from the readme file of the benchmark session, it seems like the dataset supported is "AN4, TEDLIUM, Voxforge, Common Voice and LibriSpeech", and `/data` also contains scripts to download these raw datasets. But in the paper, the benchmark dataset is CMU-ARCTIC? I was just wondering how I'm able to get the benchmarking datasets (i.e. its corresponding preprocessing scripts) for DeepSpeech2 as described in table1 of the paper. Thanks!

**Comment by aurickq** [comment]
Hi @lynnliu030. The CMU-ARCTIC dataset we used can be found as a subset of the VoxForge dataset. Will add the manifest files we used to access that subset.

**Comment by aurickq** [comment]
https://github.com/petuum/adaptdl/blob/osdi21-artifact/benchmark/models/deepspeech2/data/cmu-arctic-manifests.tar.gz

**Comment by lynnliu030** [comment]
@aurickq Thanks!
